import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>

        <h2>Our contacts:</h2>
        <ul>
            <li>
                <Link href='/about/contacts'>contacts</Link>
            </li>
            <li>
                <Link href='/about/team'>team</Link>
            </li>
        </ul>
        <div>{children}</div>
    </div>
  )
}
